### ISSUE TITLE
Need help :)

### ISSUE THREAD

**Issue by starjyunnn** [snsttr/diwa#1]
Sorry, after done setup, I tried to register a user but it asks for 4 digit invitation code. Do I need to figure it out myself or there is actually 4 digit code stated? Thanks!

**Comment by snsttr** [comment]
The invitation code can be configured in app/config.php. The default code is 3702 :-)

**Comment by starjyunnn** [comment]
Thank you for the fast response. :)

**Comment by galiptalhaerbas** [comment]
Sir without know default code, how to bypass this section
